export const SEARCH_FOCUSED = 'Header/search_focused'
export const SEARCH_BLUR = 'Header/search_blur'
export const CHANGE_LIST = 'Header/change_list'
export const MOUSE_ENTER = 'Header/mouse_enter'
export const MOUSE_LEAVE = 'Header/mouse_Leave'
export const CHANGE_PAGE = 'Header/change_page'
